apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
      - name: boardgame-app
        image: <your-dockerhub-username>/boardgame-app:latest # This will be dynamically replaced
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  type: LoadBalancer # Use NodePort for minikube/kind
  selector:
    app: boardgame-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
