apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
      - name: boardgame-app
        image: yashasdocker/boardgame-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        # Add resources limits
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Add readiness probe
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        # Add liveness probe
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  type: LoadBalancer
  selector:
    app: boardgame-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
