apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  labels:
    app: boardgame-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
      - name: boardgame-app
        image: yashasdocker/boardgame-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  labels:
    app: boardgame-app
spec:
  type: LoadBalancer
  selector:
    app: boardgame-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
